spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_bancario_dev
spring.datasource.username=seu_usuario_dev
spring.datasource.password=sua_senha_dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect 