spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_bancario_prod
spring.datasource.username=seu_usuario_prod
spring.datasource.password=sua_senha_prod
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect 